import type {
  Station,
  Train,
  Route,
  Alert,
  Transit,
  User,
} from '../types';

// ============================================================
// MOCK DATA — Rete Ferroviaria Piemonte-Lombardia
// ============================================================

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'tecnico1',
    role: 'tecnico',
    displayName: 'Marco Ferretti',
    avatarInitials: 'MF',
  },
  {
    id: 'u2',
    username: 'admin1',
    role: 'amministratore',
    displayName: 'Laura Bianchi',
    avatarInitials: 'LB',
  },
  {
    id: 'u3',
    username: 'tecnico2',
    role: 'tecnico',
    displayName: 'Giuseppe Rossi',
    avatarInitials: 'GR',
  },
  {
    id: 'u4',
    username: 'admin2',
    role: 'amministratore',
    displayName: 'Chiara Moretti',
    avatarInitials: 'CM',
  },
];

export const MOCK_STATIONS: Station[] = [
  {
    id: 'st-TO',
    code: 'TO',
    name: 'Torino Porta Nuova',
    city: 'Torino',
    status: 'operativa',
    coordinates: { x: 120, y: 200 },
    lastHeartbeat: Date.now(),
    platforms: 8,
  },
  {
    id: 'st-AL',
    code: 'AL',
    name: 'Alessandria Centrale',
    city: 'Alessandria',
    status: 'operativa',
    coordinates: { x: 320, y: 260 },
    lastHeartbeat: Date.now(),
    platforms: 6,
  },
  {
    id: 'st-AT',
    code: 'AT',
    name: 'Asti',
    city: 'Asti',
    status: 'guasta',
    coordinates: { x: 240, y: 300 },
    lastHeartbeat: Date.now() - 120000,
    platforms: 4,
    faultDescription: 'Binario 2 interrotto — deragliamento treno merci',
    faultSince: Date.now() - 3600000,
    operatorsDispatched: false,
  },
  {
    id: 'st-MI',
    code: 'MI',
    name: 'Milano Centrale',
    city: 'Milano',
    status: 'operativa',
    coordinates: { x: 500, y: 160 },
    lastHeartbeat: Date.now(),
    platforms: 12,
  },
  {
    id: 'st-GE',
    code: 'GE',
    name: 'Genova Piazza Principe',
    city: 'Genova',
    status: 'operativa',
    coordinates: { x: 340, y: 420 },
    lastHeartbeat: Date.now(),
    platforms: 6,
  },
  {
    id: 'st-NO',
    code: 'NO',
    name: 'Novara',
    city: 'Novara',
    status: 'manutenzione',
    coordinates: { x: 310, y: 160 },
    lastHeartbeat: Date.now(),
    platforms: 5,
    faultDescription: 'Manutenzione programmata binari 3-4',
    faultSince: Date.now() - 7200000,
  },
  {
    id: 'st-VC',
    code: 'VC',
    name: 'Vercelli',
    city: 'Vercelli',
    status: 'operativa',
    coordinates: { x: 215, y: 168 },
    lastHeartbeat: Date.now(),
    platforms: 3,
  },
  {
    id: 'st-CN',
    code: 'CN',
    name: 'Cuneo',
    city: 'Cuneo',
    status: 'operativa',
    coordinates: { x: 140, y: 370 },
    lastHeartbeat: Date.now(),
    platforms: 4,
  },
  {
    id: 'st-PV',
    code: 'PV',
    name: 'Pavia',
    city: 'Pavia',
    status: 'offline',
    coordinates: { x: 430, y: 230 },
    lastHeartbeat: Date.now() - 600000,
    platforms: 4,
    faultDescription: 'Stazione offline — heartbeat mancante da 10 min',
    faultSince: Date.now() - 600000,
  },
  {
    id: 'st-PC',
    code: 'PC',
    name: 'Piacenza',
    city: 'Piacenza',
    status: 'operativa',
    coordinates: { x: 570, y: 240 },
    lastHeartbeat: Date.now(),
    platforms: 5,
  },
];

export const MOCK_ROUTES: Route[] = [
  {
    id: 'rt-001',
    name: 'Torino — Milano via Novara',
    code: 'TO-MI-001',
    stationIds: ['st-TO', 'st-VC', 'st-NO', 'st-MI'],
    trainIds: ['tr-001', 'tr-002'],
    travelTimes: [25, 18, 32],
    active: true,
    createdAt: Date.now() - 86400000 * 30,
  },
  {
    id: 'rt-002',
    name: 'Alessandria — Milano via Pavia',
    code: 'AL-MI-002',
    stationIds: ['st-AL', 'st-PV', 'st-MI'],
    trainIds: ['tr-003'],
    travelTimes: [40, 28],
    active: true,
    createdAt: Date.now() - 86400000 * 20,
  },
  {
    id: 'rt-003',
    name: 'Torino — Genova via Asti-Alessandria',
    code: 'TO-GE-003',
    stationIds: ['st-TO', 'st-AT', 'st-AL', 'st-GE'],
    trainIds: ['tr-004', 'tr-005'],
    travelTimes: [45, 20, 70],
    active: true,
    createdAt: Date.now() - 86400000 * 15,
  },
  {
    id: 'rt-004',
    name: 'Torino — Cuneo',
    code: 'TO-CN-004',
    stationIds: ['st-TO', 'st-CN'],
    trainIds: ['tr-006'],
    travelTimes: [55],
    active: true,
    createdAt: Date.now() - 86400000 * 10,
  },
  {
    id: 'rt-005',
    name: 'Milano — Piacenza',
    code: 'MI-PC-005',
    stationIds: ['st-MI', 'st-PC'],
    trainIds: ['tr-007'],
    travelTimes: [38],
    active: true,
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'rt-006',
    name: 'Novara — Alessandria',
    code: 'NO-AL-006',
    stationIds: ['st-NO', 'st-VC', 'st-AT', 'st-AL'],
    trainIds: ['tr-008'],
    travelTimes: [20, 30, 22],
    active: false,
    createdAt: Date.now() - 86400000 * 2,
  },
];

export const MOCK_TRAINS: Train[] = [
  {
    id: 'tr-001',
    convoglio: 'IC 351',
    status: 'in_viaggio',
    currentStationId: null,
    nextStationId: 'st-VC',
    previousStationId: 'st-TO',
    routeId: 'rt-001',
    direction: 'andata',
    arrivalTime: Date.now() + 420000,
    departureTime: Date.now() - 300000,
    delayMinutes: 0,
    passengers: 247,
    lastUpdate: Date.now(),
    progressPercent: 35,
  },
  {
    id: 'tr-002',
    convoglio: 'REG 2847',
    status: 'in_stazione',
    currentStationId: 'st-NO',
    nextStationId: 'st-MI',
    previousStationId: 'st-VC',
    routeId: 'rt-001',
    direction: 'andata',
    arrivalTime: Date.now() + 1920000,
    departureTime: Date.now() + 300000,
    delayMinutes: 8,
    passengers: 183,
    lastUpdate: Date.now(),
    progressPercent: 0,
  },
  {
    id: 'tr-003',
    convoglio: 'FR 9612',
    status: 'in_ritardo',
    currentStationId: null,
    nextStationId: 'st-MI',
    previousStationId: 'st-PV',
    routeId: 'rt-002',
    direction: 'andata',
    arrivalTime: Date.now() + 720000,
    departureTime: Date.now() - 600000,
    delayMinutes: 22,
    passengers: 412,
    lastUpdate: Date.now(),
    progressPercent: 68,
  },
  {
    id: 'tr-004',
    convoglio: 'IC 721',
    status: 'guasto',
    currentStationId: 'st-AT',
    nextStationId: 'st-AL',
    previousStationId: 'st-TO',
    routeId: 'rt-003',
    direction: 'andata',
    arrivalTime: null,
    departureTime: null,
    delayMinutes: 45,
    passengers: 156,
    lastUpdate: Date.now(),
    progressPercent: 0,
  },
  {
    id: 'tr-005',
    convoglio: 'REG 1234',
    status: 'in_viaggio',
    currentStationId: null,
    nextStationId: 'st-GE',
    previousStationId: 'st-AL',
    routeId: 'rt-003',
    direction: 'andata',
    arrivalTime: Date.now() + 3000000,
    departureTime: Date.now() - 120000,
    delayMinutes: 5,
    passengers: 89,
    lastUpdate: Date.now(),
    progressPercent: 20,
  },
  {
    id: 'tr-006',
    convoglio: 'REG 4455',
    status: 'in_stazione',
    currentStationId: 'st-TO',
    nextStationId: 'st-CN',
    previousStationId: null,
    routeId: 'rt-004',
    direction: 'andata',
    arrivalTime: Date.now() + 600000,
    departureTime: Date.now() + 600000,
    delayMinutes: 0,
    passengers: 67,
    lastUpdate: Date.now(),
    progressPercent: 0,
  },
  {
    id: 'tr-007',
    convoglio: 'ES 7811',
    status: 'in_viaggio',
    currentStationId: null,
    nextStationId: 'st-PC',
    previousStationId: 'st-MI',
    routeId: 'rt-005',
    direction: 'andata',
    arrivalTime: Date.now() + 1200000,
    departureTime: Date.now() - 900000,
    delayMinutes: 0,
    passengers: 312,
    lastUpdate: Date.now(),
    progressPercent: 55,
  },
  {
    id: 'tr-008',
    convoglio: 'REG 9933',
    status: 'soppresso',
    currentStationId: 'st-NO',
    nextStationId: null,
    previousStationId: null,
    routeId: 'rt-006',
    direction: 'andata',
    arrivalTime: null,
    departureTime: null,
    delayMinutes: 0,
    passengers: 0,
    lastUpdate: Date.now(),
    progressPercent: 0,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'al-001',
    type: 'stazione_guasta',
    severity: 'critical',
    message: 'Stazione AT (Asti) — Binario 2 interrotto a causa di deragliamento treno merci. Traffico sospeso.',
    stationId: 'st-AT',
    trainId: 'tr-004',
    timestamp: Date.now() - 3600000,
    acknowledged: false,
  },
  {
    id: 'al-002',
    type: 'heartbeat_mancante',
    severity: 'critical',
    message: 'Stazione PV (Pavia) — Heartbeat mancante da oltre 10 minuti. Possibile offline.',
    stationId: 'st-PV',
    timestamp: Date.now() - 600000,
    acknowledged: false,
  },
  {
    id: 'al-003',
    type: 'ritardo',
    severity: 'warning',
    message: 'Treno FR 9612 — Ritardo di 22 minuti sulla tratta AL-MI-002.',
    trainId: 'tr-003',
    stationId: 'st-MI',
    timestamp: Date.now() - 1200000,
    acknowledged: false,
  },
  {
    id: 'al-004',
    type: 'treno_fermo',
    severity: 'critical',
    message: 'Treno IC 721 fermo in stazione AT (Asti) da oltre 45 minuti. Guasto rilevato.',
    trainId: 'tr-004',
    stationId: 'st-AT',
    timestamp: Date.now() - 2700000,
    acknowledged: true,
  },
  {
    id: 'al-005',
    type: 'treno_soppresso',
    severity: 'warning',
    message: 'Treno REG 9933 soppresso. Tratta NO-AL-006 non attiva.',
    trainId: 'tr-008',
    timestamp: Date.now() - 7200000,
    acknowledged: true,
    resolvedAt: Date.now() - 7000000,
  },
  {
    id: 'al-006',
    type: 'ritardo',
    severity: 'info',
    message: 'Treno REG 2847 — Ritardo di 8 minuti. Partenza da NO posticipata.',
    trainId: 'tr-002',
    stationId: 'st-NO',
    timestamp: Date.now() - 300000,
    acknowledged: false,
  },
];

export const MOCK_TRANSITS: Transit[] = [
  {
    id: 'tr-log-001',
    trainId: 'tr-001',
    stationId: 'st-TO',
    type: 'uscita',
    timestamp: Date.now() - 300000,
    delayed: false,
    delayMinutes: 0,
  },
  {
    id: 'tr-log-002',
    trainId: 'tr-002',
    stationId: 'st-VC',
    type: 'uscita',
    timestamp: Date.now() - 900000,
    delayed: false,
    delayMinutes: 0,
  },
  {
    id: 'tr-log-003',
    trainId: 'tr-002',
    stationId: 'st-NO',
    type: 'ingresso',
    timestamp: Date.now() - 600000,
    delayed: true,
    delayMinutes: 8,
  },
  {
    id: 'tr-log-004',
    trainId: 'tr-003',
    stationId: 'st-AL',
    type: 'uscita',
    timestamp: Date.now() - 1800000,
    delayed: true,
    delayMinutes: 15,
  },
  {
    id: 'tr-log-005',
    trainId: 'tr-004',
    stationId: 'st-AT',
    type: 'ingresso',
    timestamp: Date.now() - 3600000,
    delayed: false,
    delayMinutes: 0,
  },
];
